name:                day1
version:             0.1.0.0
github:              "githubuser/day1"
license:             BSD3
author:              "Thomas Whiteway"
maintainer:          "thomas.whiteway@gmail.com"
copyright:           "2020 Thomas Whiteway"

dependencies:
- base >= 4.7 && < 5
- containers

executables:
  day1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
